version: "3.8"
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:80"
    environment:
      - NAME=World
